WebCalc/Controllers/CalcController.cs
using DomainModels.Repository;
using ReactCalc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCalc.Models;

namespace WebCalc.Controllers
{
    [Authorize]
    public class CalcController : Controller
    {
        private IORRepository ORRepository { get; set; }
        private IUserRepository UserRepository { get; set; }
        private IOperationRepository OperationRepository { get; set; }

        private Calc Calc { get; set; }

        public CalcController(IORRepository orrepository, 
            IUserRepository UserRepository, 
            IOperationRepository OperationRepository)
        {
            Calc = new Calc();
            ORRepository = orrepository;
            this.UserRepository = UserRepository;
            this.OperationRepository = OperationRepository;
        }

        public ActionResult Index()
        {
            var model = new CalcModel();
            model.OperationList = Calc.Operations.Select(o => new SelectListItem() { Text = $"{o.Name}", Value = $"{o.Name}" });
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(CalcModel model)
        {
            model.OperationList = Calc.Operations.Select(o => new SelectListItem() { Text = $"{o.Name}", Value = $"{o.Name}", Selected = model.Operation == o.Name});

            var operation = Calc.Operations.FirstOrDefault(o => o.Name == model.Operation);
            if (operation != null)
            {
                var dbOper = OperationRepository.GetByName(operation.Name);
                var operId = dbOper.Id;
                var inputData = string.Join(",", model.Arguments);

                var oldResult = ORRepository.GetOldResult(operId, inputData);
                if (!double.IsNaN(oldResult))
                {
                    model.Result = oldResult;
                }
                else
                {
                    #region Вычисление
                    model.Result = operation.Execute(model.Arguments);

                    var rec = ORRepository.Create();

                    // текущего пользователя назначаем автором
                    var currUser = UserRepository.GetByName(User.Identity.Name);
                    rec.AuthorId = currUser.Id;

                    rec.OperationId = operId;

                    rec.ExecutionDate = DateTime.Now;
                    rec.ExecutionTime = new Random().Next(0, 100);
                    rec.InputData = inputData;
                    rec.Result = model.Result ?? Double.NaN;

                    ORRepository.Update(rec);
                    #endregion
                }
                return View(model);
            }

            return View();
        }
    }
}

WebCalc/Controllers/OperationResultController.cs
using DomainModels.Repository;
using System.Web.Mvc;
using System.Linq;

namespace WebCalc.Controllers
{
    public class OperationResultController : BaseController
    {
        public OperationResultController(IORRepository orrepository, IUserRepository UserRepository, IOperationRepository OperationRepository, ILikeRepository LikeRepository)
            : base(orrepository, UserRepository, OperationRepository, LikeRepository)
        {
        }

        public ActionResult Index()
        {
            var curUser = GetCurrentUser();

            var results = ORRepository.GetByUser(curUser);

            var likes = LikeRepository.GetAll()     // получаем все лайки
                .Where(u => u.UserId == curUser.Id) // фильтруем по текущему юзеру
                .Select(it => it.ResultId);         // достаем из лайков результаты операций  

            foreach (var result in results)
            {
                result.IsLiked = likes.Contains(result.Id);
            }

            return View(results);
        }

        [HttpPost]
        public JsonResult Like(long id)
        {
            var result = ORRepository.Get(id);
            if (result == null)
            {
                return Json(new { Success = false, Error = "Не удалось найти результат" });
            }

            // Получить текущего юзера
            var curUser = GetCurrentUser();

            var like = LikeRepository.GetAll().FirstOrDefault(it => it.UserId == curUser.Id && it.ResultId == id);

            if (like != null)
            {
                LikeRepository.Delete(like);
                return Json(new { Success = true, Name = "like" });
            }

            // Создать лайк
            like = LikeRepository.Create();

            // Заполнить свойства
            like.UserId = curUser.Id;
            like.ResultId = result.Id;

            // Сохранить
            LikeRepository.Update(like);

            // Вернуться к списку операций
            return Json(new { Success = true, Name = "dislike" });
        }
    }
}

WebCalc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Calc</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ReactCalc", "Index", "Calc", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Операции", "Index", "Operation")</li>
                    <li>@Html.ActionLink("История вычислений", "Index", "OperationResult")</li>
                </ul>


                @if (Request.IsAuthenticated)
            {
                    <b>
                        @(User.Identity.Name)
                    </b>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink("Выйти", "Logout", "Account")
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Calc</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>